cart/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    #url(r'^remove/(?P<cartno>\d+'*'+)/$', views.cart_remove, name='cart_remove2'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path('remove/<str:cartno>', views.cart_remove, name='cart_remove2'),
    path('add/<str:cartno>', views.cart_add2, name='cart_add2'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from newapi import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('pages.urls')),
    path('payments', include('payments.urls')), 
    url(r'^employees/', views.employeeList.as_view(),name='emplist'),
    #url(r'^g/$', views.gv(), name='g'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#   url(r'^admin/', admin.site.urls),
#]

pages/urls.py
from django.urls import path
from. import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pages'

urlpatterns = [
	path('',views.home, name='home'),
	path('createpost/',views.createpost, name='createpost') ,
	path('confirm',views.customerorder, name='co') ,
	url(r'^list/$',views.product_list, name='product_list') ,
	url(r'^list/(?P<pk>[0-9]+)/$',views.category_select, name='category_select'),
	url(r'^contact/$', views.contactview, name='contact'),
	path('about/',views.about, name='about') ,
	#path('contact/',views.contact, name='contact') ,
	#path('contact/r^(?P<mid>[1-9]+)/$',views.mid, name='mid') ,
	#path('contact/page<int:num>/', views.mid),
	#url(r'^contact/(?P<mid>\d+)/$', views.mid, name='mid'),
	#url(r'^details/(?P<key>[0-9]+)/$', views.mid, name='mid'),
	url(r'^index/$',views.IndexView.as_view(), name='index') ,
	#url(r'^list$',views.product_list, name='list') ,
	url(r'^indexproducts/$',views.pindex, name='indexp') ,
	#url(r'^indexproducts/(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='productdetail') ,
	url(r'^indexproducts/(?P<pk>[0-9]+)/$',views.product_detail, name='productdetail') ,
	#url(r'^indexproducts/(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='pdetail') ,
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='mid'),
	url(r'^index/add/$', views.MusicianCreate.as_view(), name='addm'),
	#path('index/',views.index, name='index') ,
	#url(r'^indexstar/',views.indexs, name='indexs'),
	path('indexstar/',views.indexs, name='indexs'),
	url(r'^indexstar/f/$', views.indexstar, name='indexf'),
	url(r'^blogadd/$', views.showform, name='blogadd'),
	url(r'^(?P<id>\d+)/edit/$', views.editpost, name='editpost'),
	url(r'^(?P<id>\d+)/delete/$', views.musician_delete_view, name='deletepost'),
	url(r'^test1/$',views.test1, name='test1') ,
	url(r'^indexproducts/(?P<pk>[0-9]+)/confirm.html',views.confirm, name='confirm') ,
	url(r'^try/$', views.aindex, name='try'),
    url(r'^ajax/', views.ajax,name='aj'),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

#from django.conf.urls import url
#from django.contrib import admin

#from mysite.views import hello

#urlpatterns = [
#   url(r'^admin/', admin.site.urls),
#   url(r'^hello/$', hello),
#

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(str(i), str(i)) for i in range(1, 26)]

pcolor='black, red'

#PRODUCT_COLORS = (( 'white', 'white'), ('blue', 'blue'), ('red', 'red'))
SIZE_CHOICES = (( 'S', 'S'), ('M', 'M'), ('L', 'L'))  
INTEGER_CHOICES= [tuple([x,x]) for x in range(1,32)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    #size = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_SIZES)
    #color = forms.CharField(choices=PRODUCT_COLORS)
    #pcolor='black, red'
    
    size= forms.CharField(label="Please choose a size:", widget=forms.Select(choices=SIZE_CHOICES))
    #color= forms.CharField(label="Please choose a color:", widget=forms.Select(choices=PRODUCT_COLORS))
    #color= forms.CharField(label="Please choose a color:", widget=forms.Select(choices=getcolor(pcolor)))
    update = forms.BooleanField(label="", required=False, initial=False, widget=forms.HiddenInput)
class CartShowProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    #size = forms.CharField()
    #color = forms.CharField()
    update = forms.BooleanField(label="", required=False, initial=False, widget=forms.HiddenInput)

pages/templates/author.html
<form action="{% url 'update-author' ????? %}" method="post">
        {% csrf_token %}
        {% for author in authors %}
        <input type="radio" name="choice" id="{{ author.id }}" value="{{ author.id }}">
        <label for="author">{{ author.first_name}} {{ author.last_name}}</label><br>
        {% endfor %}
        <input type="submit" value="Update">
    </form>

pages/templates/confirms.html
{% extends "base.html" %}
{% load static %}

{% block tit %}
Your order is {{ss}}!
{% endblock %}


{%block content%}


{% endblock %}

pages/templates/createpost.html
<head>
<title>Create a Post </title>
</head>

<body>
<h2>Customer Information </h2>

<form action="" method="POST">
{% csrf_token %}

First name:<br>
<input type="text" name="first_name"  >
<br>
Last name:<br>
<input type="text" name="last_name">
<br>Delivery Address:<br>
<input type="text" name="address" >
<br>
Email:<br>
<input type="text" name="email">
<br>Mobile:<br>
<input type="text" name="mobile" >
<br>

Delivery-all delivery will be $10<br>

  <select name="delivery">
    <option value="tnt">tnt</option>
    <option value="toll">toll</option>
   
  </select>
<br>

Payment method<br>

  <select name="payment">
    <option value="cash">tnt</option>
    <option value="paypal">toll</option>
   
  </select>

  
<br>
Note for this transaction:<br>
<input type="text" name="note">
<input type="submit" value="Submit"/>
</form>
{{ss}}
</body>

</html>

pages/templates/details.html
{% load static %}

{% block tit %}
Welcome to Visit Roy Home Page!
{% endblock %}


{%block content%}

<h3><a href={% url 'editpost' musician.id %}>update</a>
<a href={% url 'deletepost' musician.id %}>delete</a><h3>
</br>
 {{redirect}}
</br></br>
</h3>
</h3>

	  <image src="/media/{{musician.pic}}" class="d-block w-100" width=300 height=300 alt="...">
  <br>

 


 My ID is: {{musician.id}}<br>
        My first name is: {{musician.first_name}}<br>
        My instrument is: {{musician.instrument}}



    



{% endblock %}

pages/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block tit %}
Welcome to Visit Roy Home Page!
{% endblock %}


{%block content%}
 {{ mybrother.namer }}
<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/p2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/p1.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5> label 2</h5>
          <p>p1.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/p3.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>P3.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Roy Liao</h5>
    <p class="card-text">np quick examples text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">About</a>
  </div>
</div>
<form class="form-inline">
  <label class="sr-only" for="inlineFormInputName2">Name</label>
  <input type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Jane Doe">

  <label class="sr-only" for="inlineFormInputGroupUsername2">Username</label>
  <div class="input-group mb-2 mr-sm-2">
    <div class="input-group-prepend">
      <div class="input-group-text">@</div>
    </div>
    <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Username">
  </div>

  <div class="form-check mb-2 mr-sm-2">
    <input class="form-check-input" type="checkbox" id="inlineFormCheck">
    <label class="form-check-label" for="inlineFormCheck">
      Remember me
    </label>
  </div>

  <button type="submit" class="btn btn-primary mb-2">Submit</button>
</form>
{% endblock %}

pages/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block tit %}
Welcome to Visit Roy Home Page!
{% endblock %}


{%block content%}
 
<style >
  .container { font-size: 0; }
.container div { display: inline-block; font-size: 12px; margin-left: 10px; margin-top: 10px;marker-start: 0}
 
</style>



 <img src="{% static 'images/p2.jpg' %}" class="d-block w-100" alt="...">
<h3><a href={% url 'home' %}>Back to Home</a></h3>
</br>
</br>
<div class="container">
      {% for  musician in all_musicians %}
      <div id=content">
    
        <span>
        <image src="/media/{{musician.pic}}" class="d-block w-15" width=255 height=260 alt="..."></image>
        </span><a href={% url 'mid' musician.id %}>{{musician.first_name}}</a>	{{musician.last_name}}	{{musician.instrument}}
    
       </div>
       {% endfor %}
</div>
     
     

       



 {{ mybrother.namer }}
{% endblock %}

pages/templates/indexproduct.html
{% extends "base.html" %}
{% load static %}

{% block tit %}
{% block title %}
   Products 
{% endblock %}
{% endblock %}


{%block content%}
 
<style >
  .container { font-size: 0; }
.container div { display: inline-block; font-size: 12px; margin-left: 0px; margin-top: 10px;marker-start: 0}
 
</style>

<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h6>Categories</h6>
            <ol class="list-unstyled">
              <li style=" float: left;display: block;
  color: white;
  text-align: center;
  padding: 6px;
  text-decoration: none " {% if not category %} class="active"{% endif %}><a href='/list' ><span> All </span></a></li>
            {% for c in categories %}

              <li style=" float: left; display: block;
  color: white;
  text-align: center;
  padding: 6px;
  text-decoration: none" {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}"> <span> {{ c.name }} </span> </a>
              </li>
            {% endfor %}
            </ol>
          </div>
</div><!-- blog-sidebar -->


<div class="container">
      {% for  all_products in all_products %}
      <div id=content">
    
        <span>
        <a href={% url 'pages:productdetail' all_products.id %}><image src="/media/{{all_products.pic}}" class="d-block w-15" width=255 height=270 alt="..."></image></a>
        </span><a href={% url 'pages:productdetail' all_products.id %}>{{all_products.p_name}}</a>	{{all_products.price}}
    
       </div>
       {% endfor %}
</div>

<div class="container">
      {% for  all_products in products %}
      <div id=content">
    
        <span>
        <a href={% url 'pages:productdetail' all_products.id %}><image src="/media/{{all_products.pic}}" class="d-block w-15" width=255 height=270 alt="..."></image></a>
        </span><a href={% url 'pages:productdetail' all_products.id %}>{{all_products.p_name}}</a>	{{all_products.price}}
    
       </div>
       {% endfor %}
</div>

 

     
     

       




{% endblock %}

pages/templates/indexstar.html
{% extends "base.html" %}
{% load static %}

{% block tit %}
Welcome to Visit Roy Home Page!
{% endblock %}



{%block content%}
 <img src="{% static 'images/p2.jpg' %}" class="d-block w-100" alt="...">
<h3><a href={% url 'home' %}>Back to Home</a></h3>
{{redirect}}
  {% if errormsg  %}
  <P><strong>{{errormsg}}</strong></P>
  {% endif %}
  <form action="{% url 'indexf' %}" method="post">
    {% csrf_token %}
    {% for  musician in all_musicians %}
       
       <input type="radio" name="musician" id="musician{{forloop.counter}}" value="{{musician.id}}">

       <label for="musician{{forloop.counter}}">
         {{musician.first_name}}
         {% if musician.isf  %}
          <img src="{% static 'images/g.png' %}">

         {% endif %}
       </label>
        </br>
     
    {% endfor %}
        </br>
    <input type="submit" name="submit" value="Favorite">
  </form>

  

  {% endblock %}

pages/templates/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center">Kshs. {{ product.price }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href='' >All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

pages/templates/pdetails.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
   Product Detail
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <image src="/media/{{object.pic}}" class="d-block w-100" width=300 height=350 alt="...">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ product.p_name>
                           
                            <p class="text-muted">Kshs. {{ product.price }}</p>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                            <p>{{ product.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

pages/templates/productdetails3.html
<!doctype html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>     
</head>
<body>
<div class='row'>
                <div class="card" class="col-md-6 text-right">
                    <div class="card-body">
                        <div >
                            <image src="/media/{{product.pic}}" class="d-block w-100" width=336 height=420 alt="..."></image>
                
                        
                            {{ product.p_name}}
                       
                            <p class="text-muted">Price {{ product.price }}</p>
                            </div> 
                             
                            
                  
                 
                </div>

              </div>
         
              <div class="col-md-6" style="padding-right: : 20px">
                <div>{{ product.description|safe|linebreaksbr }}</div><br>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {% csrf_token %}

<select id="select1">
             <option value="joshua">joshua</option>
             <option value="peter">peter</option>

        </select>
       
        


                                {% for field in cart_product_form %}
                                <div class="form_group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                          <span class="text-danger small">{{field.errors}}</span>
                                        </div>
                                         
                                              {{field.label_tag}}
                                         
                                               {{field}}
     
                                      
                                     {% endfor %}

                                      
                                        <div class="col-sm-offset-2 col-sm-10">
                                          <span class="text-danger small"></span>
                                        </div>
                                         
                                              <label for="id_color">Please choose a color:</label>
                                
                                 <select name="color" id="id_color">

                                {% for color in pcolor %}
                                    
                                        
                                          
                                            <option value={{color}}>{{color}}</option>
                                         
                                             

                                        
                                {% endfor %}
</div>
                            </div>


                                 <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                          </div>

<script type="text/javascript">
var previous = "initial prev value";
var newvalue
$("select").live('click', function () {
        //update previous value
        previous = $(this).val();
    }).change(function() {
        alert('old value:'+previous); //I have previous value 
        newvalue=$(this).val();
        alert('new selected:'+newvalue);
        $.post('/ajax/', {color:newvalue}, function(data) {
          alert(data['foo']);      
         });
    });
</script> 

   
      </body>
    </html>

pages/templates/productdetailsbackup.html
{% extends 'base.html' %}
{% load static %}

{% block tit %}
Welcome to Visit Roy Home Page!
{% endblock %}



{%block content%}

 
   <div class='row'>
                <div class="card" class="col-md-6 text-right">
                    <div class="card-body">
                        <div >
                            <image src="/media/{{product.pic}}" class="d-block w-100" width=336 height=420 alt="..."></image>
                
                        
                            {{ product.p_name}}
                       
                            <p class="text-muted">Price {{ product.price }}</p>
                            </div> 
                             
                            
                  
                 
                </div>

              </div>
             

              <div class="col-md-6" style="padding-right: : 20px">
                <div>{{ product.description|safe|linebreaksbr }}</div><br>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                {% for field in cart_product_form %}
                                <div class="form_group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                          <span class="text-danger small">{{field.errors}}</span>
                                        </div>
                                         
                                              {{field.label_tag}}
                                         
                                               {{field}}
     
                                      
                                     {% endfor %}

                                      
                                        <div class="col-sm-offset-2 col-sm-10">
                                          <span class="text-danger small"></span>
                                        </div>
                                         
                                              <label for="id_color">Please choose a color:</label>
                                
                                 <select name="color" id="id_color">

                                {% for color in pcolor %}
                                    
                                        
                                          
                                            <option value={{color}}>{{color}}</option>
                                         
                                             

                                        
                                {% endfor %}
                               
       
     <script type="text/javascript">

var previous = "initial prev value";
var newvalue
$("#id_color").live('click', function () {
        //update previous value
        previous = $(this).val();
    }).change(function() {
        alert('old value:'+previous); //I have previous value 
        newvalue=$(this).val();
        alert('new selected:'+newvalue);
        $.post('/ajax/', {color:newvalue}, function(data) {
          alert(data['foo']);
       
         });
    });

       </script>


                              </div>
                            </div>


                                 <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                          </div>
                
<select id="select1">
             <option value="joshua">joshua</option>
             <option value="peter">peter</option>

</select>
       
     <script type="text/javascript">

var previous = "initial prev value";
var newvalue
$("select1").live('click', function () {
        //update previous value
        previous = $(this).val();
    }).change(function() {
        alert('old value:'+previous); //I have previous value 
        newvalue=$(this).val();
        alert('new selected:'+newvalue);
        $.post('/ajax/', {color:newvalue}, function(data) {
          alert(data['foo']);
       
         });
    });

       </script>
       
         
{% endblock %}
 

pages/templates/productdetailsbackup3.html
<!doctype html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>     
</head>
<body>
<div class='row'>
                <div class="card" class="col-md-6 text-right">
                    <div class="card-body">
                        <div >
                            <image src="/media/{{product.pic}}" class="d-block w-100" width=336 height=420 alt="..."></image>
                
                        
                            {{ product.p_name}}
                       
                            <p class="text-muted">Price {{ product.price }}
                            {{ product.p_code }}</p>
                        </div> 
                             
                            
                  
                 
                    </div>

                </div>
         
                <div class="col-md-6" style="padding-right: : 20px">
                    <div>{{ product.description|safe|linebreaksbr }}{{ product.p_code }}
                    </div>
                    <div id='slevel'>
                      
                    </div><br>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                {% for field in cart_product_form %}
                                  <div class="form_group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                          <span class="text-danger small">{{field.errors}}</span>
                                        </div>
                                         
                                              {{field.label_tag}}
                                         
                                               {{field}}
                                          
                                           {% endfor %}

                                      
                                        <div class="col-sm-offset-2 col-sm-10">
                                          <span class="text-danger small"></span>
                                        </div>
                                         
                                              <label for="id_color">Please choose a color:</label>
                                
                                             <select name="color" id="id_color">

                                            {% for color in pcolor %}                          
                                          
                                               <option value={{color}}>{{color}}
                                               </option>
                                                                          
                                             {% endfor %}
                                     </div>
                                  </div>


                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                    </div>
<script type="text/javascript">
var previous = "initial prev value";
var newvalue 

$( document ).ready(function() {
        //alert("hi roy") 
        color=$("#id_color option:selected").html();
        size=$("#id_size").val();
        qty=$("#id_quantity").val();

       //alert('new selected color:'+color);
       $.post('/ajax/', {pcode:"{{ product.p_code }}",color:color,size:size,quantity:qty}, function(data) {
        //  alert(data['color']);
        //  alert(data['size']);
        //  alert(data['quantity']);
        //  alert(data['pcode']);    
        //  alert(data['stock']);  
          $("#slevel").text('Current Stock Level:'+(data['stock']));  
         });
});

</script> 

<script type="text/javascript">
var previous = "initial prev value";
var newvalue 

$("select").live('click', function () {
        
        previous = $(this).val();
    }).change(function() {
      //alert('product:'+'{{ product.p_code }}');
       // alert('old value:'+previous); //I have previous value 
        newvalue=$(this).val();
        color=$("#id_color option:selected").html();
        size=$("#id_size").val();
        qty=$("#id_quantity").val();

       //alert('new selected color:'+color);
       
        
        $.post('/ajax/', {pcode:"{{ product.p_code }}",color:color,size:size,quantity:qty}, function(data) {
         // alert(data['color']);
        //  alert(data['size']);
        //  alert(data['quantity']);
        //  alert(data['pcode']);    
        //  alert(data['stock']);  
          $("#slevel").text('Current Stock Level:'+(data['stock']));  
         });
    });
</script> 

   
      </body>
    </html>

pages/templates/test3.html
<html>
<body>
<select id="select_dropdown">
  <option value="joshua">joshua</option>
  <option value="peter">peter</option>

</select>
 
<script type="text/javascript">
$(document).ready(function(){

$('#select_dropdown').change(function(){
var e = document.getElementById("select_dropdown");
var value = e.options[e.selectedIndex].value;
document.write(value)

$.ajax({
    url: "your-url",
    type: "post", // or "get"
    data: value,
    success: function(data) {

        alert(data.result);
    }});
});
</script>
<center><small>Copyright &copy RoyHome.org. All rights Reserved!</small></center>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  </body>
</html>