cart/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    #url(r'^remove/(?P<cartno>\d+'*'+)/$', views.cart_remove, name='cart_remove2'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path('remove/<str:cartno>', views.cart_remove, name='cart_remove2'),
    path('add/<str:cartno>', views.cart_add2, name='cart_add2'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from newapi import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('pages.urls')),
    path('payments', include('payments.urls')), 
    url(r'^employees/', views.employeeList.as_view(),name='emplist'),
    #url(r'^g/$', views.gv(), name='g'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#   url(r'^admin/', admin.site.urls),
#]

pages/urls.py
from django.urls import path
from. import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pages'

urlpatterns = [
	path('',views.home, name='home'),
	path('createpost/',views.createpost, name='createpost') ,
	path('confirm',views.customerorder, name='co') ,
	url(r'^list/$',views.product_list, name='product_list') ,
	url(r'^list/(?P<pk>[0-9]+)/$',views.category_select, name='category_select'),
	url(r'^contact/$', views.contactview, name='contact'),
	path('about/',views.about, name='about') ,
	#path('contact/',views.contact, name='contact') ,
	#path('contact/r^(?P<mid>[1-9]+)/$',views.mid, name='mid') ,
	#path('contact/page<int:num>/', views.mid),
	#url(r'^contact/(?P<mid>\d+)/$', views.mid, name='mid'),
	#url(r'^details/(?P<key>[0-9]+)/$', views.mid, name='mid'),
	url(r'^index/$',views.IndexView.as_view(), name='index') ,
	#url(r'^list$',views.product_list, name='list') ,
	url(r'^indexproducts/$',views.pindex, name='indexp') ,
	#url(r'^indexproducts/(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='productdetail') ,
	url(r'^indexproducts/(?P<pk>[0-9]+)/$',views.product_detail, name='productdetail') ,
	#url(r'^indexproducts/(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='pdetail') ,
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='mid'),
	url(r'^index/add/$', views.MusicianCreate.as_view(), name='addm'),
	#path('index/',views.index, name='index') ,
	#url(r'^indexstar/',views.indexs, name='indexs'),
	path('indexstar/',views.indexs, name='indexs'),
	url(r'^indexstar/f/$', views.indexstar, name='indexf'),
	url(r'^blogadd/$', views.showform, name='blogadd'),
	url(r'^(?P<id>\d+)/edit/$', views.editpost, name='editpost'),
	url(r'^(?P<id>\d+)/delete/$', views.musician_delete_view, name='deletepost'),
	url(r'^test1/$',views.test1, name='test1') ,
	url(r'^indexproducts/(?P<pk>[0-9]+)/confirm.html',views.confirm, name='confirm') ,
	url(r'^try/$', views.aindex, name='try'),
    url(r'^ajax/', views.ajax,name='aj'),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

#from django.conf.urls import url
#from django.contrib import admin

#from mysite.views import hello

#urlpatterns = [
#   url(r'^admin/', admin.site.urls),
#   url(r'^hello/$', hello),
#

payments/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views
app_name = 'payments'
urlpatterns = [
	#path('/homep', views.callback, name='homep'),
    path('/homep', views.HomePageView.as_view(), name='homep'),
    path('charge/', views.charge, name='charge'), # new
    url(r'^create/$', views.order_create, name='order_create'),

   # url(r'^paypal/', include('paypal.standard.ipn.urls')),
	path('/payment_process', views.payment_process, name='payment_process' ),
	url(r'^payment_done/$', TemplateView.as_view(template_name= "payments/payment_done.html"), name='payment_done'),
	url(r'^payment_canceled/$', TemplateView.as_view(template_name= "paymments/payment_cancelled.html"), name='payment_canceled'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(str(i), str(i)) for i in range(1, 26)]

pcolor='black, red'

#PRODUCT_COLORS = (( 'white', 'white'), ('blue', 'blue'), ('red', 'red'))
SIZE_CHOICES = (( 'S', 'S'), ('M', 'M'), ('L', 'L'))  
INTEGER_CHOICES= [tuple([x,x]) for x in range(1,32)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    #size = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_SIZES)
    #color = forms.CharField(choices=PRODUCT_COLORS)
    #pcolor='black, red'
    
    size= forms.CharField(label="Please choose a size:", widget=forms.Select(choices=SIZE_CHOICES))
    #color= forms.CharField(label="Please choose a color:", widget=forms.Select(choices=PRODUCT_COLORS))
    #color= forms.CharField(label="Please choose a color:", widget=forms.Select(choices=getcolor(pcolor)))
    update = forms.BooleanField(label="", required=False, initial=False, widget=forms.HiddenInput)
class CartShowProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    #size = forms.CharField()
    #color = forms.CharField()
    update = forms.BooleanField(label="", required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from pages.models import Products
from .cart import Cart
from .forms import CartAddProductForm, CartShowProductForm
import json  


@require_POST
def cart_addsimple(request, product_id):
    
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')
def cart_add(request, product_id):
    
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    
    color=request.POST.get('color')
    print(color)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'],color=color, size=cd['size'])
    return redirect('cart:cart_detail')
def cart_add2(request, cartno):
    y = cartno.split("*")
    if y!= "":
            product_id=int(y[0])
            color=y[1]
            size=y[2]
            cart = Cart(request)
            product = get_object_or_404(Products, id=product_id)
            form = CartShowProductForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'],color=color, size=size)
                return redirect('cart:cart_detail')

def cart_remove(request,cartno):
    cart = Cart(request)
    #product = get_object_or_404(Products, id=product_id)
    cart.remove(cartno)
    return redirect('cart:cart_detail')


def cart_detail(request):
    
    cart = Cart(request)
    for item in cart:
        product = get_object_or_404(Products, id=item['product_id'])
        prodpic=product.pic
        item['update_quantity_form'] = CartShowProductForm(initial={'quantity': item['quantity'], 'update': True})
        item['prodpic']=prodpic
        item['cartno']=item['product_id']+'*'+item['color']+'*'+item['size']
        item['product']=product
    #jcart=json.stringify(cart)
    #scart=encodeURI(cart)
   
    return render(request, 'cart/detail.html', {'cart': cart, })

cart/templates/cart/detail.html
{% extends "base.html" %}

{% load static %}
{% block title %}
    Your Shopping Cart

{% endblock %}

{% block content %}

        <div class="row" style="margin-top: 6%">
        <h4>Your Shopping Cart

           
        </h4>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Size</th>
                        <th>Colour</th>
                        <th>Quantity</th>
                        <th>Remove</th>

                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if item.prodpic %} {{ item.prodpic.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 100px; width: auto">
                                </a>
                            </td>
                            <td>{{ item.prodname }}</td>
                            <div class="unselectable" unselectable="yes" onselectstart="return false;"/>
                            <td> {{ item.size }}</td>
                            <td> {{ item.color }}</td>
                                    </div>
                            <form action="{% url 'cart:cart_add2' item.cartno %}" method="post">
                                    {% csrf_token %}
                                    
                            <td>
                                
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                            </form>
                            </td>
                            <td>
                                <a href="{% url 'cart:cart_remove2' item.cartno %}">Remove</a>
                            </td>
                             
                            <td>{{ item.price }}</td>
                            <td>{{ item.total_price }}</td>
                         
                           
                        </tr>
                   
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>$ {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>

            <br>
        <div class="text-right">
            <a href="{% url 'pages:product_list' %}" class="btn btn-default">Continue Shopping</a>
             <a href="{% url 'payments:order_create' %}" class="btn btn-primary">Checkout</a>
        </div>
        </div>

{% endblock %}

cart/templates/cart/detailbackup.html
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h4>Your Shopping Cart

            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                       
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h4>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Size</th>
                        <th>Colour</th>
                        <th>Quantity</th>
                        <th>Remove</th>

                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.pic %} {{ product.pic.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 100px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.p_name }}</td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                            <td> {{ item.update_quantity_form.size }}</td>
                            <td> {{ item.update_quantity_form.color }}</td>
                            <td>
                                
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                            </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>kshs. {{ item.price }}</td>
                            <td>kshs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url 'pages:index' %}" class="btn btn-default">Continue Shopping</a>
            <a href="" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}

cart/templates/cart/detailbk2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart

{% endblock %}

{% block content %}

        <div class="row" style="margin-top: 6%">
        <h4>Your Shopping Cart

            <span class="badge pull-right" >
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                       
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} items {{ totail_items|pluralize }}, $ {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h4>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Size</th>
                        <th>Colour</th>
                        <th>Quantity</th>
                        <th>Remove</th>

                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if item.prodpic %} {{ item.prodpic.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 100px; width: auto">
                                </a>
                            </td>
                            <td>{{ item.prodname }}</td>
                            <form action="{% url 'cart:cart_add' item.product_id %}" method="post">
                                    {% csrf_token %}
                                    <div class="unselectable" unselectable="yes" onselectstart="return false;"/>
                            <td> {{ item.update_quantity_form.size }}</td>
                            <td> {{ item.update_quantity_form.color }}</td>
                                    </div>
                            <td>
                                
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                            </form>
                            </td>
                            <td>
                                <a href="{% url 'cart:cart_remove2' item.cartno %}">Remove</a>
                            </td>
                             
                            <td>{{ item.price }}</td>
                            <td>{{ item.total_price }}</td>
                            <td>{{item}}
                            </td>
                        </tr>
                   
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>

            <br>
        <div class="text-right">
            <a href="{% url 'pages:index' %}" class="btn btn-default">Continue Shopping</a>
            <a href="" class="btn btn-primary">Checkout</a>
        </div>
        </div>

{% endblock %}