cart/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    #url(r'^remove/(?P<cartno>\d+'*'+)/$', views.cart_remove, name='cart_remove2'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path('remove/<str:cartno>', views.cart_remove, name='cart_remove2'),
    path('add/<str:cartno>', views.cart_add2, name='cart_add2'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from newapi import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('pages.urls')),
    path('payments', include('payments.urls')), 
    url(r'^employees/', views.employeeList.as_view(),name='emplist'),
    #url(r'^g/$', views.gv(), name='g'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#   url(r'^admin/', admin.site.urls),
#]

orders/urls.py
from . import views
from django.urls import path
from django.conf.urls import include, url


app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    path('create/<str:cart>', views.order_create2, name='order_create2'),
    url(r'^likePost/(?P<pk>[0-9]+)/$', views.likePost, name='likepost'),   # likepost view at /likepost
    url(r'^postlist/$', views.postlist, name='postlist'),
    url(r'^postlist/ajax2/', views.ajax2,name='aj2'),
    url(r'^commentpost/(?P<pk>[0-9]+)/$', views.commentpost, name='commentpost'),
    
]

orders/models.py
from django.db import models
from pages.models import Products
from django.db.models import Count




class Order(models.Model):
    STATE_CHOICES = (
    ('STATE', (
            ('NSW', 'NSW'),
            ('VIC', 'VIC'),
            ('SA', 'SA'),
            ('TAS', 'TAS'),
            ('ACT', 'ACT'),
            ('NT', 'NT'),
            ('WA', 'WA'),
        ),
    
    ),
    )
    
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    postal_code = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100, choices=STATE_CHOICES,default='NSW')
    country = models.CharField(max_length=100,default='AUSTRALIA')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Products, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
   
    colour = models.CharField(max_length=100, blank=True)
    size = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

class Post(models.Model):
        post_heading = models.CharField(max_length=200)
        user = models.CharField(max_length=50)
        password = models.CharField(max_length=50)
        name=models.CharField(max_length=50)
        email=models.CharField(max_length=100)
        post_text = models.TextField()
        def __unicode__(self):      # If python2 use __str__ if python3
            return unicode(self.user)
class Like(models.Model):
        post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
        post_text2 = models.TextField()

        def __str__(self):
            return self.post_text2

        def get_like_number(self):
            like_count =len(models.Like.objects.filter(post_text2='like'))
            return like_count




# Create your models here.

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city','state','country']

orders/views.py
from django.shortcuts import render, get_object_or_404
from .models import OrderItem,Post
from .forms import OrderCreateForm
from cart.cart import Cart
from payments.views import *
from pages.models import Products,Sku
from .models import Post, Like
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.db.models import Count

def order_create(request):
    #cart=scart
    
    cart = Cart(request)

    print(cart.cart)
    #request.session['cart']=cart
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(False)
            for item in cart:
                print(item)
                product_id=item['product_id']
                quantity=item['quantity']                 
                product = get_object_or_404(Products, id=product_id)
                sproduct = Sku.objects.filter(product= product,colour=item['color'],size=item['size'])
                if sproduct.count() == 0:
                    stock=0
                    
                else:
                    
                    order = form.save()
                    stock=sproduct[0].stock
                    OrderItem.objects.create(
                    order=order,
                    product=product,
                    price=item['price'],
                    size=item['size'],
                    colour=item['color'],
                    quantity=item['quantity'],
                )
                    print(sproduct[0].stock)
                    id=sproduct[0].id
                    print(id)
                    newq=Sku.objects.get(id=id)
                    newstock=int(sproduct[0].stock)-quantity
                    newq.stock=newstock
                    newq.save()
                    print('after:'+str(newstock))
                
            
            last_name=str(form.cleaned_data.get("last_name"))
            #streetno=str(form.cleaned_data.get("first_name"))
            address=str(form.cleaned_data.get("address"))
            suburb=str(form.cleaned_data.get("city"))
            post_code=str(form.cleaned_data.get("postal_code"))
            state=str(form.cleaned_data.get("state"))
            country=str(form.cleaned_data.get("country"))

            name=''
            email=''
            total=0
            comment='<p>Your order will be delivered to:</p>'+'</br>'+address+'</br>'+suburb+'</br>'+state+' '+country+'<br><br><p>You Ordeded the Folllowing:</p> </br>'
            name= str(form.cleaned_data.get("first_name"))+' '+last_name
            email=str(form.cleaned_data.get("email"))
            for item in cart:

                comment=comment+'<h4>'+item['prodname'] +':</h4>Quantity: '+str(item['quantity'])+' Price:'+str(item['price'])+' Size: ' + item['size'] +' Color: ' +   item['color']  +'<br>'+' Subtotal: '+str(item['total_price'])+'<br>'
                total=total+item['total_price']#subject= name + " with the email" + email + "sent the following message:" + comment;
           
            #send_mail('Thanks for the  order!', comment, 'yunzhi.liao@gmail.com', [email])
            comment=comment+'<p><br><h4>Total: '+str(total)+'</h4></p>'
            msg = EmailMessage('Thanks '+name+', Your order is confirmed!!', comment, 'yunzhi.liao@gmail.com', [email])
            msg.content_subtype = "html"  
            #msg.attach_file('')
            msg.send()
            cart.clear()
        return render(request, 'orders/order/created.html', {'order': order, 'cart':cart})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/homep.html', {'form': form, 'cart':cart},)

def order_create2(request,cart):
    #cart=scart
    request.session['foo']='bar'
    x=request.session.get('foo')

    cart = Cart(request)
    #request.session['cart']=cart
    form = OrderCreateForm()
    if request.method == 'POST':
        print('PPPPPPPPPPPPPPPPPPPPPPP')
        form = OrderCreateForm(request.POST)
        pass
            #cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        
        print(cart)
        print('nnnnnnnnnnnnnnnnnnnnnnnnnnnn')
        return render(request, 'orders/order/create.html', { 'form': form,'cart':cart,'x':x})
def postlist(request):
        posts = Post.objects.all().annotate(ml=Count("likes"))
        likeg = Like.objects.filter(post_text2='like').annotate(mll=Count("post_text2"))
        #print(likeg[3])
        context_dict={}
        for post in posts: 
            #print(post.ml)
            likeno = Like.objects.filter(post=post,post_text2='like').count()
            post.lk=likeno
            #post.objects.annotate(mylike=likeno)
            context_dict['posts'] = post
            context_dict['likes'] = likeno
            #print(context_dict)
            print(post)
        likenum=Like.objects.filter(post_text2='like').count()
        #print(context_dict) # Getting all the posts from database
        return render(request, 'orders/order/postlist.html', { 'posts': posts, 'likenum':likenum})    

def likePost(request,pk):
        print('roy')
        if request.method == 'GET':
               post_id = request.GET['post_id']

               likedpost = Post.obejcts.get(pk=post_id) #getting the liked posts
               m = Like(post=likedpost) # Creating Like Object
               m.save()  # saving it to store in database
               return HttpResponse("Success!") # Sending an success response
        else:
               return HttpResponse("Request method is not a GET")
import json      
from django.http import HttpResponse
from django.template import Template, Context
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def ajax2(request):
    print('hi')
    if request.method == "POST": #os request.GET()
        print(request)
        print('roy')
        post_id=request.POST['post_id'].strip()
        thetext=request.POST['thetext'].strip()
        thecomment=request.POST['thecomment'].strip()
        if thetext=='Like':
            thecomment='like'
        post=Post.objects.get(pk=post_id)
        print(thecomment)
        textpost = Like(post=post,post_text2=thecomment)
        textpost.save()
        likenum=Like.objects.filter(post_text2='like').count()
        print(likenum)
        


        #sproduct=Sku.objects.raw('SELECT * FROM pages_sku ')
            
        
    """returns json response"""
    #newvalue='roy'
    return HttpResponse(json.dumps({'stock': post_id,'likenum': likenum,'thecomment':thecomment}), content_type="application/json")

def ajax3(request):
    print('hi')
    if request.method == "POST": #os request.GET()
        print(request)
        print('roy')
        post_id=request.POST['post_id'].strip()
        thecomment=request.POST['thecomment'].strip()
        post=Post.objects.get(pk=post_id)
        print(thecomment)
        textpost = Like(post=post,post_text2=thecomment)
        textpost.save()

        #sproduct=Sku.objects.raw('SELECT * FROM pages_sku ')
            
        
    """returns json response"""
    #newvalue='roy'
    return HttpResponse(json.dumps({'stock': post_id,'thecomment':thecomment}), content_type="application/json")

def commentpost(request,pk):
    
    if request.method == "POST":
        print('hi comment')
        print(request)
        print(pk)
        comment=request.POST.get('mycomment')
        print(comment)
        
        #sproduct=Sku.objects.raw('SELECT * FROM pages_sku ')
            
        
    """returns json response"""
    #newvalue='roy'
    return HttpResponse(json.dumps({'stock':'comment'}), content_type="application/json")

orders/templates/orders/order/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
<style>
.container {
  width: 1000px;
  clear: both;
}

.container input {
  width: 100%;
  clear: both;
}
 
</style>

    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-6">
                <h4 class="page-header">Checkout</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <input type="submit" class="btn btn-primary" value="Submit order">
                </form>
            </div>
            <div class="col-md-6">
                
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }} x {{ item.price }}  --  {{ item.size }}  --  {{ item.color }} -- {{ item.prodname }}
                        <span>= $ {{ item.total_price }}</span>
                        
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: $ {{ cart.get_total_price }}</li>
                </ul>
             
            </div>
        </div>
    </div>
    
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                {% if order.id %}
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
                {% else %}
                <p>  <strong>oops! The stock has run out.</strong> Can you please call for back order?</p>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/homep.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}

<style>
.container {
  width: 1000px;
  clear: both;
}

.container input {
  width: 100%;
  clear: both;
}
 
</style>

  
    


    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-6">
                <h4 class="page-header">Checkout</h4>
                <form action="{% url 'charge' %}" method="post">
                    {% csrf_token %}
                    
                    {{ form.as_p }}<br>
                    
                </form>
             <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]
                });
            },

            // Finalize the transaction
            payment: function(data, actions) {
  return actions.payment.create({
    transactions: [{
      amount: {
        total: '30.11',
        currency: 'USD',
        details: {
          subtotal: '30.00',
          tax: '0.07',
          shipping: '0.03',
          handling_fee: '1.00',
          shipping_discount: '-1.00',
          insurance: '0.01'
        }
      },
      description: 'The payment transaction description.',
      custom: '90048630024435',
      //invoice_number: '12345', Insert a unique invoice number
      payment_options: {
        allowed_payment_method: 'INSTANT_FUNDING_SOURCE'
      },
      soft_descriptor: 'ECHI5786786',
      item_list: {
        items: [
        {
          name: 'hat',
          description: 'Brown hat.',
          quantity: '5',
          price: '3',
          tax: '0.01',
          sku: '1',
          currency: 'USD'
        },
        {
          name: 'handbag',
          description: 'Black handbag.',
          quantity: '1',
          price: '15',
          tax: '0.02',
          sku: 'product34',
          currency: 'USD'
        }],
        shipping_address: {
          recipient_name: 'Brian Robinson',
          line1: '4th Floor',
          line2: 'Unit #34',
          city: 'San Jose',
          country_code: 'US',
          postal_code: '95131',
          phone: '011862212345678',
          state: 'CA'
        }
      }
    }],
    note_to_payer: 'Contact us for any questions on your order.'
  });
},



        }).render('#paypal-button-container');
    </script>   
            </div>
            <div class="col-md-6">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }} x {{ item.price }}  --  {{ item.size }}  --  {{ item.color }} -- {{ item.prodname }}
                        <span>= $ {{ item.total_price }}</span>
                        
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: $ {{ cart.get_total_price }}</li>
                </ul>
                <br>
                <script src="https://checkout.stripe.com/checkout.js"  class="stripe-button"
                     data-key="{{ key }}"
                     data-description="Payment Information"
                     data-amount="500"
                     data-locale="auto"></script>
             
            </div>

        </div>
    </div>
    
{% endblock %}




<h2>Buy for $5.00</h2>
<form action="{% url 'charge' %}" method="post">
  {% csrf_token %}
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="{{ key }}"
          data-description="Payment Information"
          data-amount="500"
          data-locale="auto"></script>
</form>
<div id='back'>
{% if status  %}
  <P><strong>{{status}}</strong></P>
  
  {% else %}
  <P><strong>Oops, your payment is NOT processed!</strong></P>
  {% endif %}




</div>

orders/templates/orders/order/postlist.html
<!DOCTYPE html>
<html>
<head>
    <title>Like Post App</title>
</head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


 
    {% for post in posts %}


    <h3>{{ forloop.counter }}) {{ post.post_heading }} </h3>
      
        {% for detail in post.likes.all %}      
              
             {% if  detail.post_text2 == "like" %}
             
        Yeh, you like it!!
            {% else %}
                <p>{{ detail.post_text2 }} </p>
            {% endif%}
               
        {% endfor %}



 
<div id="likemessage" style="height: 30px; color:green">  {{ post.lk }} People Like So Far!<image style="height: 30px" src='\media\likeimg.png'></div>

    <p id="message{{post.id}}"></p>
    <textarea id="mycomment{{post.id}}" rows="3" cols="50">My comment:</textarea>
    <br>
    <button id="like{{post.id}}" name="like{{post.id}}" value="{{post.id}}">Your Comment  </button>

    <button id="comment{{post.id}}" name="comment{{post.id}}" value="{{post.id}}">Like </button>
    <br><br>
    
    
  
  
  {% endfor %}

  
<br>


<script>
    
  $("button").click(function() {
    
    var fired_button = $(this).val();
    alert(fired_button);
    var fired_text = $(this).text();
    alert(fired_text);
    var thecomment=$('#mycomment'.concat(fired_button)).val();
    //var thelike=$('#comment'.concat(fired_button)).val();
    //alert(thelike);
    
    $.ajax(
    {
        type:"POST",
        url: "ajax2/",

        data:{
                 post_id: fired_button, thecomment: thecomment, thetext: fired_text
        },
        success: function( data ) 
        {
         alert(data['stock']);
         alert('thecomment:'+data['thecomment']);
         alert('thelike:'+data['likenum']);

        $( '#message'.concat(fired_button)).html( "<span style='background:red' > <b>Like this~~</b></span>");

       
        location.reload();
        }
     })
});

  
</script>

</body>
</html>

orders/templates/orders/order/postlistbk.html
<!DOCTYPE html>
<html>
<head>
    <title>Like Post App</title>
</head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
 
    {% for post in posts %}
    <h3>{{ forloop.counter }}) {{ post.post_heading }}</h3>
    <p>{{ post.post_text }} </p>
    <p id="message{{post.id}}"></p>
    <button id="like{{post.id}}" name="like{{post.id}}" value="{{post.id}}">LIKE this  </button>

    <button id="comment{{post.id}}" name="comment{{post.id}}" value="comment{{post.id}}">Your Comment  </button>
    <br><br>



  <textarea name="mycomment" rows="3" cols="50">The cat was playing in the garden.</textarea>
  <br>
   <a id="sub{{post.id}}" href="{% url 'orders:commentpost' post.id %}" class="btn btn-primary">Submit My Comment</a>
   <div id=subcomment{{post.id}} value='{{post.id}}'>submit comment</div>
   <div id=substatus{{post.id}} value='{{post.id}}'>status</div>
   <script type="text/javascript"> 

        $("div").click(function() {
         var fired_btn = $(this).html()

         
         alert(fired_btn);
         var myid={{post.id}};
         alert(myid);


    $.ajax(
    {
        type:"POST",
        url: "ajax2/",
        data:{
                 post_id: fired_btn
        },
        success: function( data ) 
        {
         alert(data['stock']);
            $( '#message'.concat(fired_btn)).html( "<span style='background:red' > <b>Like this~~</b></span>");
        }
     })
});


    </script>
  {% endfor %}
<br>


<script>
  $("button").click(function() {
    var fired_button = $(this).val();
    alert(fired_button);
    $(document).ready(function () {
    if ($("textarea").value !== "") {
        alert($("textarea").value);
    }

});
    $.ajax(
    {
        type:"POST",
        url: "ajax2/",
        data:{
                 post_id: fired_button
        },
        success: function( data ) 
        {
         alert(data['stock']);
            $( '#message'.concat(fired_button)).html( "<span style='background:red' > <b>Like this~~</b></span>");
        }
     })
});

  
</script>

</body>
</html>