cart/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    #url(r'^remove/(?P<cartno>\d+'*'+)/$', views.cart_remove, name='cart_remove2'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path('remove/<str:cartno>', views.cart_remove, name='cart_remove2'),
    path('add/<str:cartno>', views.cart_add2, name='cart_add2'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from newapi import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('pages.urls')),
    path('payments', include('payments.urls')), 
    url(r'^employees/', views.employeeList.as_view(),name='emplist'),
    #url(r'^g/$', views.gv(), name='g'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#from django.conf.urls import url
#from django.contrib import admin

#urlpatterns = [
#   url(r'^admin/', admin.site.urls),
#]

payments/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views
app_name = 'payments'
urlpatterns = [
	#path('/homep', views.callback, name='homep'),
    path('/homep', views.HomePageView.as_view(), name='homep'),
    path('charge/', views.charge, name='charge'), # new
    url(r'^create/$', views.order_create, name='order_create'),

   # url(r'^paypal/', include('paypal.standard.ipn.urls')),
	path('/payment_process', views.payment_process, name='payment_process' ),
	url(r'^payment_done/$', TemplateView.as_view(template_name= "payments/payment_done.html"), name='payment_done'),
	url(r'^payment_canceled/$', TemplateView.as_view(template_name= "paymments/payment_cancelled.html"), name='payment_canceled'),

]

payments/models.py
from django.db import models


# Create your models here.

payments/views.py
from django.shortcuts import render, get_object_or_404,redirect
from orders.models import OrderItem
from orders.forms import OrderCreateForm
from cart.cart import Cart
from pages.models import Products,Sku
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.core.mail import send_mail
import stripe # new
from django.conf import settings
from django.views.generic.base import TemplateView
from django.urls import reverse
#from paypal.standard.forms import PayPalPaymentsForm


def payment_process(request):
    host = request.get_host()
    print(host)
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': '0.50',
        'item_name': 'Item_Name_clothing',
        'invoice': 'Test Payment Invoice 3',
        'currency_code': 'USD',
        #'notify_url': 'http://{}{}'.format(host, reverse('paypal-ipn')),
        #'return_url': 'http://{}{}'.format(host, reverse('payment_done')),
        #'cancel_return': 'http://{}{}'.format(host, reverse('payment_canceled')),
    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request, 'payment_process.html', {'form': form})


stripe.api_key = settings.STRIPE_SECRET_KEY # new



class HomePageView(TemplateView):
    template_name = 'homep.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


def charge(request): # new
    cart = Cart(request)
    amt=cart.get_total_price2()
    customer=request.POST['first_name']+' '+request.POST['last_name']+','+request.POST['email']+' purchased on web'
    print(amt)
    if request.method == 'POST':

        charge = stripe.Charge.create(
            amount=int(amt),
            currency='aud',
            description=customer,
            source=request.POST['stripeToken']
            
        )
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(False)
            for item in cart:
                print(item)
                product_id=item['product_id']
                quantity=item['quantity']                 
                product = get_object_or_404(Products, id=product_id)
                sproduct = Sku.objects.filter(product= product,colour=item['color'],size=item['size'])
                if sproduct.count() == 0:
                    stock=0
                    
                else:
                    order.paid=True
                    order = form.save()

                    stock=sproduct[0].stock
                    OrderItem.objects.create(
                    order=order,
                    product=product,
                    price=item['price'],
                    size=item['size'],
                    colour=item['color'],
                    quantity=item['quantity'],
                                   )
                    print(sproduct[0].stock)
                    id=sproduct[0].id
                    print(id)
                    newq=Sku.objects.get(id=id)
                    newstock=int(sproduct[0].stock)-quantity
                    newq.stock=newstock
                    newq.save()
                    print('after:'+str(newstock))
                
            
            
            cart.clear()
            #return redirect('payments:homep')
        return render(request, 'orders/order/created.html', {'order': order, 'cart':cart})
    else:
        form = OrderCreateForm()
        print('blank')
    return render(request, 'homep.html', {'form': form, 'cart':cart,})
        
def callback(request):
 
  #profile = UserProfile.objects.get(user=request.user)

  r = request.POST('https://connect.stripe.com/oauth/token', params={
    'client_secret': settings.STRIPE_SECRET_KEY
  
  }).json()

  try:
    access_token = r['access_token']
    refresh_token = r['refresh_token']
    publishable_key = r['stripe_publishable_key']
    #profile.save()

    messages.success(request, "Your account was successfully connected to Stripe.")
  except KeyError:
    messages.error(request, "Unable to connect your account to Stripe.")

  return redirect('homep')

def order_create(request):
    #cart=scart
    
    cart = Cart(request)

    
    print(cart.cart)
    #request.session['cart']=cart
    if request.method == 'POST':
        print('start to work on db')
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(False)
            for item in cart:
                print(item)
                product_id=item['product_id']
                quantity=item['quantity']                 
                product = get_object_or_404(Products, id=product_id)
                sproduct = Sku.objects.filter(product= product,colour=item['color'],size=item['size'])
                if sproduct.count() == 0:
                    stock=0
                    
                else:
                    
                    order = form.save()
                    stock=sproduct[0].stock
                    OrderItem.objects.create(
                    order=order,
                    product=product,
                    price=item['price'],
                    size=item['size'],
                    colour=item['color'],
                    quantity=item['quantity'],
                )
                    print(sproduct[0].stock)
                    id=sproduct[0].id
                    print(id)
                    newq=Sku.objects.get(id=id)
                    newstock=int(sproduct[0].stock)-quantity
                    newq.stock=newstock
                    newq.save()
                    print('after:'+str(newstock))
                
            
            
            cart.clear()
            #return redirect('payments:homep')
        return render(request, 'orders/order/created.html', {'order': order, 'cart':cart})
    else:
        form = OrderCreateForm()
        print('blank')
    return render(request, 'homep.html', {'form': form, 'cart':cart,})

payments/templates/charge.html
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

payments/templates/homep.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
<style>
.container {
  width: 1000px;
  clear: both;
}

.container input {
  width: 100%;
  clear: both;
}
 
</style>
<div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-6">
                <h4 class="page-header">Checkout</h4>
                <form action="{% url 'payments:charge' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}<br>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_test_fBgqSs4c818IP0JbscIlkSAy00x06h7EGB"
          data-description="Payment Information"
          data-amount={{ cart.get_total_price2 }}
          data-locale="auto"></script>
           
</form>
            </div>
            <div class="col-md-6">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }} x {{ item.price }}  --  {{ item.size }}  --  {{ item.color }} -- {{ item.prodname }}
                        <span>= $ {{ item.total_price }}</span>
                        
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: $ {{ cart.get_total_price }}</li>
            </br>
            <div id="paypal-button-container"></div>
               
    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>
    
    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
    
            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: "{{ cart.get_total_price }}"
                        }
                    }]
                });
            },
    
            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }
    
    
        }).render('#paypal-button-container');
    </script>
            </ul>
         
        </div>



                </ul>
             
            </div>
        </div>
    </div>


{% endblock %}

payments/templates/homepaypal.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
<style>
.container {
  width: 1000px;
  clear: both;
}

.container input {
  width: 100%;
  clear: both;
}
 
</style>

<div class="col-md-6">
        <div class="page-header">
            Your Order
        </div>
        <ul class="list-group">
            {% for item in cart %}
                <li class="list-group-item">
                {{ item.quantity }} x {{ item.price }}  --  {{ item.size }}  --  {{ item.color }} -- {{ item.prodname }}
                <span>= $ {{ item.total_price }}</span>
                
                </li>
            {% endfor %}

        <li class="list-group-item active">Total Cost: $ {{ cart.get_total_price }}</li>
    </br>
        <div id="paypal-button-container"></div>
           
<!-- Include the PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

<script>
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: "{{ cart.get_total_price }}"
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // Show a success message to the buyer
                alert('Transaction completed by ' + details.payer.name.given_name + '!');
            });
        }


    }).render('#paypal-button-container');
</script>
        </ul>
     
    </div>


{% endblock %}

payments/templates/homepb4merge.html
<h2>Buy for $5.00</h2>
<form action="{% url 'charge' %}" method="post">
  {% csrf_token %}
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="{{ key }}"
          data-description="Payment Information"
          data-amount="500"
          data-locale="auto"></script>
</form>
<div id='back'>
{% if status  %}
  <P><strong>{{status}}</strong></P>
  
  {% else %}
  <P><strong>Oops, your payment is NOT processed!</strong></P>
  {% endif %}




</div>

payments/templates/homeppayok.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
<style>
.container {
  width: 1000px;
  clear: both;
}

.container input {
  width: 100%;
  clear: both;
}
 
</style>


<h2>Order</h2>
<form action="{% url 'payments:charge' %}" method="post">
  {% csrf_token %}
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_test_fBgqSs4c818IP0JbscIlkSAy00x06h7EGB"
          data-description="Payment Information"
          data-amount="1438"
          data-locale="auto"></script>
</form>
<div id='back'>
{% if status  %}
  <P><strong>{{status}}</strong></P>
  
  {% else %}
  <P><strong>Oops, your payment is NOT processed!</strong></P>
  {% endif %}




</div>




    
{% endblock %}

payments/templates/payment_cancelled.html
payment cancelled!

payments/templates/payment_done.html
payment done!

payments/templates/payment_process.html
{{ form.render }}